// Reference-only phrasing lookup table for the gap-phrasing matrix.
// Generated by an agent given the granularity model, snap-forward
// semantics, and phrasing style guide. Keyed by '<priorId>__<currentId>',
// each value has 'nextAvailable' (scenario A) and 'pushedForward'
// (scenario B) phrasings.
//
// **NOT USED AT RUNTIME** — this is reference data the writer can
// use to verify the template-based rendering below produces the
// right output. The shipped renderer is template-driven (a small
// set of base phrases with placeholders that get filled from the
// actual gap minutes / prior bucket / current bucket / scenario)
// rather than a 625-entry lookup. Keep this file as a fixture so
// the templates can be cross-checked against an exhaustive output.
//
// 25 TOD options on each side -> 625 entries.
// The exact-tier IDs (t-exact-XXXX) are representative samples; the
// phrasings generalise so any HH:MM in the same bucket reads the same.
//
 
export const GAP_PHRASING_REFERENCE = {
  "t-none__t-none": {
    "nextAvailable": "right after",
    "pushedForward": "the next day"
  },
  "t-none__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-none__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-none__t-lbl-predawn": {
    "nextAvailable": "later that dawn, around pre-dawn",
    "pushedForward": "the next dawn, around pre-dawn"
  },
  "t-none__t-lbl-dawn": {
    "nextAvailable": "later that dawn",
    "pushedForward": "the next dawn"
  },
  "t-none__t-lbl-sunrise": {
    "nextAvailable": "later that dawn, around sunrise",
    "pushedForward": "the next dawn, around sunrise"
  },
  "t-none__t-lbl-emorn": {
    "nextAvailable": "later that morning, around early morning",
    "pushedForward": "the next morning, around early morning"
  },
  "t-none__t-lbl-morn": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-none__t-lbl-lmorn": {
    "nextAvailable": "later that morning, around late morning",
    "pushedForward": "the next morning, around late morning"
  },
  "t-none__t-lbl-noon": {
    "nextAvailable": "later that afternoon, around noon",
    "pushedForward": "the next afternoon, around noon"
  },
  "t-none__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-none__t-lbl-laft": {
    "nextAvailable": "later that afternoon, around late afternoon",
    "pushedForward": "the next afternoon, around late afternoon"
  },
  "t-none__t-lbl-sunset": {
    "nextAvailable": "later that evening, around sunset",
    "pushedForward": "the next evening, around sunset"
  },
  "t-none__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-none__t-lbl-dusk": {
    "nextAvailable": "later that evening, around dusk",
    "pushedForward": "the next evening, around dusk"
  },
  "t-none__t-lbl-enight": {
    "nextAvailable": "later that night, around early night",
    "pushedForward": "the next night, around early night"
  },
  "t-none__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-none__t-lbl-mid": {
    "nextAvailable": "later that night, around midnight",
    "pushedForward": "the next night, around midnight"
  },
  "t-none__t-exact-0300": {
    "nextAvailable": "later that dawn",
    "pushedForward": "the next dawn"
  },
  "t-none__t-exact-0830": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-none__t-exact-1200": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-none__t-exact-1400": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-none__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-none__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-none__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-day__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-lbl-predawn": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-dawn": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-sunrise": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-emorn": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-morn": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-lmorn": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-noon": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-aft": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-laft": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-lbl-sunset": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-lbl-eve": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-lbl-dusk": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-lbl-enight": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-lbl-mid": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-exact-0300": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-exact-0830": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-exact-1200": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-exact-1400": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-broad-day__t-exact-1800": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-exact-2100": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-day__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-broad-night__t-none": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-lbl-predawn": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-dawn": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-sunrise": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-emorn": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-morn": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-lmorn": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-noon": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-aft": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-laft": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-lbl-sunset": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-lbl-eve": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-lbl-dusk": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-lbl-enight": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-lbl-mid": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-exact-0300": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-exact-0830": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-exact-1200": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-exact-1400": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-broad-night__t-exact-1800": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-exact-2100": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-broad-night__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-predawn__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-predawn__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-predawn__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-predawn__t-lbl-predawn": {
    "nextAvailable": "still around pre-dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-predawn__t-lbl-dawn": {
    "nextAvailable": "still that dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-predawn__t-lbl-sunrise": {
    "nextAvailable": "still that dawn, around sunrise",
    "pushedForward": "the next dawn"
  },
  "t-lbl-predawn__t-lbl-emorn": {
    "nextAvailable": "that morning, around early morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-predawn__t-lbl-morn": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-predawn__t-lbl-lmorn": {
    "nextAvailable": "that morning, around late morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-predawn__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-predawn__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-predawn__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-predawn__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-predawn__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-predawn__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-predawn__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-predawn__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-predawn__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-predawn__t-exact-0300": {
    "nextAvailable": "still that dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-predawn__t-exact-0830": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-predawn__t-exact-1200": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-predawn__t-exact-1400": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-predawn__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-predawn__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-predawn__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-dawn__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-dawn__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-dawn__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-dawn__t-lbl-predawn": {
    "nextAvailable": "still that dawn, around pre-dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-dawn__t-lbl-dawn": {
    "nextAvailable": "still around dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-dawn__t-lbl-sunrise": {
    "nextAvailable": "still that dawn, around sunrise",
    "pushedForward": "the next dawn"
  },
  "t-lbl-dawn__t-lbl-emorn": {
    "nextAvailable": "that morning, around early morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-dawn__t-lbl-morn": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-dawn__t-lbl-lmorn": {
    "nextAvailable": "that morning, around late morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-dawn__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-dawn__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-dawn__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-dawn__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-dawn__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-dawn__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-dawn__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-dawn__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-dawn__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-dawn__t-exact-0300": {
    "nextAvailable": "still that dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-dawn__t-exact-0830": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-dawn__t-exact-1200": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-dawn__t-exact-1400": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-dawn__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-dawn__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-dawn__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-sunrise__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-sunrise__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-sunrise__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-sunrise__t-lbl-predawn": {
    "nextAvailable": "still that dawn, around pre-dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-sunrise__t-lbl-dawn": {
    "nextAvailable": "still that dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-sunrise__t-lbl-sunrise": {
    "nextAvailable": "still around sunrise",
    "pushedForward": "the next dawn"
  },
  "t-lbl-sunrise__t-lbl-emorn": {
    "nextAvailable": "that morning, around early morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-sunrise__t-lbl-morn": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-sunrise__t-lbl-lmorn": {
    "nextAvailable": "that morning, around late morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-sunrise__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-sunrise__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-sunrise__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-sunrise__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunrise__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunrise__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunrise__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-sunrise__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-sunrise__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-sunrise__t-exact-0300": {
    "nextAvailable": "still that dawn",
    "pushedForward": "the next dawn"
  },
  "t-lbl-sunrise__t-exact-0830": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-sunrise__t-exact-1200": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-sunrise__t-exact-1400": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-sunrise__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunrise__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunrise__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-emorn__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-emorn__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-emorn__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-emorn__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-emorn__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-emorn__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-emorn__t-lbl-emorn": {
    "nextAvailable": "still around early morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-emorn__t-lbl-morn": {
    "nextAvailable": "still that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-emorn__t-lbl-lmorn": {
    "nextAvailable": "still that morning, around late morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-emorn__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-emorn__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-emorn__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-emorn__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-emorn__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-emorn__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-emorn__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-emorn__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-emorn__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-emorn__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-emorn__t-exact-0830": {
    "nextAvailable": "still that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-emorn__t-exact-1200": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-emorn__t-exact-1400": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-emorn__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-emorn__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-emorn__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-morn__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-morn__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-morn__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-morn__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-morn__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-morn__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-morn__t-lbl-emorn": {
    "nextAvailable": "still that morning, around early morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-morn__t-lbl-morn": {
    "nextAvailable": "still around morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-morn__t-lbl-lmorn": {
    "nextAvailable": "still that morning, around late morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-morn__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-morn__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-morn__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-morn__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-morn__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-morn__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-morn__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-morn__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-morn__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-morn__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-morn__t-exact-0830": {
    "nextAvailable": "still that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-morn__t-exact-1200": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-morn__t-exact-1400": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-morn__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-morn__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-morn__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-lmorn__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-lmorn__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-lmorn__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-lmorn__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-lmorn__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-lmorn__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-lmorn__t-lbl-emorn": {
    "nextAvailable": "still that morning, around early morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-lmorn__t-lbl-morn": {
    "nextAvailable": "still that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-lmorn__t-lbl-lmorn": {
    "nextAvailable": "still around late morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-lmorn__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-lmorn__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-lmorn__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-lmorn__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-lmorn__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-lmorn__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-lmorn__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-lmorn__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-lmorn__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-lmorn__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-lmorn__t-exact-0830": {
    "nextAvailable": "still that morning",
    "pushedForward": "the next morning"
  },
  "t-lbl-lmorn__t-exact-1200": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-lmorn__t-exact-1400": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-lmorn__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-lmorn__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-lmorn__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-noon__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-noon__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-noon__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-noon__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-noon__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-noon__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-noon__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-noon__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-noon__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-noon__t-lbl-noon": {
    "nextAvailable": "still around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-noon__t-lbl-aft": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-noon__t-lbl-laft": {
    "nextAvailable": "still that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-noon__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-noon__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-noon__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-noon__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-noon__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-noon__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-noon__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-noon__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-noon__t-exact-1200": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-noon__t-exact-1400": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-noon__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-noon__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-noon__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-aft__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-aft__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-aft__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-aft__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-aft__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-aft__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-aft__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-aft__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-aft__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-aft__t-lbl-noon": {
    "nextAvailable": "still that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-aft__t-lbl-aft": {
    "nextAvailable": "still around afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-aft__t-lbl-laft": {
    "nextAvailable": "still that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-aft__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-aft__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-aft__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-aft__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-aft__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-aft__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-aft__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-aft__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-aft__t-exact-1200": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-aft__t-exact-1400": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-aft__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-aft__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-aft__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-laft__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-laft__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-laft__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-lbl-laft__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-laft__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-laft__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-laft__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-laft__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-laft__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-laft__t-lbl-noon": {
    "nextAvailable": "still that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-laft__t-lbl-aft": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-laft__t-lbl-laft": {
    "nextAvailable": "still around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-laft__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-laft__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-laft__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-laft__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-laft__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-laft__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-laft__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-laft__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-laft__t-exact-1200": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-laft__t-exact-1400": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-lbl-laft__t-exact-1800": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-laft__t-exact-2100": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-laft__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-sunset__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-sunset__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-lbl-sunset__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-sunset__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-sunset__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-sunset__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-sunset__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-sunset__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-sunset__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-sunset__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-sunset__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-sunset__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-sunset__t-lbl-sunset": {
    "nextAvailable": "still around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunset__t-lbl-eve": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunset__t-lbl-dusk": {
    "nextAvailable": "still that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunset__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-sunset__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-sunset__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-sunset__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-sunset__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-sunset__t-exact-1200": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-sunset__t-exact-1400": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-sunset__t-exact-1800": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunset__t-exact-2100": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-sunset__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-eve__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-eve__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-lbl-eve__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-eve__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-eve__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-eve__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-eve__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-eve__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-eve__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-eve__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-eve__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-eve__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-eve__t-lbl-sunset": {
    "nextAvailable": "still that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-eve__t-lbl-eve": {
    "nextAvailable": "still around evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-eve__t-lbl-dusk": {
    "nextAvailable": "still that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-eve__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-eve__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-eve__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-eve__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-eve__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-eve__t-exact-1200": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-eve__t-exact-1400": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-eve__t-exact-1800": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-eve__t-exact-2100": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-eve__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-dusk__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-dusk__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-lbl-dusk__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-dusk__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-dusk__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-dusk__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-dusk__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-dusk__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-dusk__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-dusk__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-dusk__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-dusk__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-dusk__t-lbl-sunset": {
    "nextAvailable": "still that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-lbl-dusk__t-lbl-eve": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-dusk__t-lbl-dusk": {
    "nextAvailable": "still around dusk",
    "pushedForward": "the next evening"
  },
  "t-lbl-dusk__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-dusk__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-dusk__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-dusk__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-dusk__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-dusk__t-exact-1200": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-dusk__t-exact-1400": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-dusk__t-exact-1800": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-dusk__t-exact-2100": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-lbl-dusk__t-exact-2330": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-enight__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-enight__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-lbl-enight__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-enight__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-enight__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-enight__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-enight__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-enight__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-enight__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-enight__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-enight__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-enight__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-enight__t-lbl-sunset": {
    "nextAvailable": "the next evening, around sunset",
    "pushedForward": "the evening after that"
  },
  "t-lbl-enight__t-lbl-eve": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-enight__t-lbl-dusk": {
    "nextAvailable": "the next evening, around dusk",
    "pushedForward": "the evening after that"
  },
  "t-lbl-enight__t-lbl-enight": {
    "nextAvailable": "still around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-enight__t-lbl-night": {
    "nextAvailable": "still that night",
    "pushedForward": "the next night"
  },
  "t-lbl-enight__t-lbl-mid": {
    "nextAvailable": "still that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-enight__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-enight__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-enight__t-exact-1200": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-enight__t-exact-1400": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-enight__t-exact-1800": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-enight__t-exact-2100": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-enight__t-exact-2330": {
    "nextAvailable": "still that night",
    "pushedForward": "the next night"
  },
  "t-lbl-night__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-night__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-lbl-night__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-night__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-night__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-night__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-night__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-night__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-night__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-night__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-night__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-night__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-night__t-lbl-sunset": {
    "nextAvailable": "the next evening, around sunset",
    "pushedForward": "the evening after that"
  },
  "t-lbl-night__t-lbl-eve": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-night__t-lbl-dusk": {
    "nextAvailable": "the next evening, around dusk",
    "pushedForward": "the evening after that"
  },
  "t-lbl-night__t-lbl-enight": {
    "nextAvailable": "still that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-night__t-lbl-night": {
    "nextAvailable": "still around night",
    "pushedForward": "the next night"
  },
  "t-lbl-night__t-lbl-mid": {
    "nextAvailable": "still that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-night__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-night__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-night__t-exact-1200": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-night__t-exact-1400": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-night__t-exact-1800": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-night__t-exact-2100": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-night__t-exact-2330": {
    "nextAvailable": "still that night",
    "pushedForward": "the next night"
  },
  "t-lbl-mid__t-none": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-lbl-mid__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-lbl-mid__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-lbl-mid__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-mid__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-mid__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-mid__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-mid__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-mid__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-mid__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-mid__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-mid__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-mid__t-lbl-sunset": {
    "nextAvailable": "the next evening, around sunset",
    "pushedForward": "the evening after that"
  },
  "t-lbl-mid__t-lbl-eve": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-mid__t-lbl-dusk": {
    "nextAvailable": "the next evening, around dusk",
    "pushedForward": "the evening after that"
  },
  "t-lbl-mid__t-lbl-enight": {
    "nextAvailable": "still that night, around early night",
    "pushedForward": "the next night"
  },
  "t-lbl-mid__t-lbl-night": {
    "nextAvailable": "still that night",
    "pushedForward": "the next night"
  },
  "t-lbl-mid__t-lbl-mid": {
    "nextAvailable": "still around midnight",
    "pushedForward": "the next night"
  },
  "t-lbl-mid__t-exact-0300": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-lbl-mid__t-exact-0830": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-lbl-mid__t-exact-1200": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-mid__t-exact-1400": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-lbl-mid__t-exact-1800": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-mid__t-exact-2100": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-lbl-mid__t-exact-2330": {
    "nextAvailable": "still that night",
    "pushedForward": "the next night"
  },
  "t-exact-0300__t-none": {
    "nextAvailable": "later that dawn",
    "pushedForward": "the next dawn"
  },
  "t-exact-0300__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-exact-0300__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-exact-0300__t-lbl-predawn": {
    "nextAvailable": "still that dawn, around pre-dawn",
    "pushedForward": "the next dawn"
  },
  "t-exact-0300__t-lbl-dawn": {
    "nextAvailable": "still that dawn",
    "pushedForward": "the next dawn"
  },
  "t-exact-0300__t-lbl-sunrise": {
    "nextAvailable": "still that dawn, around sunrise",
    "pushedForward": "the next dawn"
  },
  "t-exact-0300__t-lbl-emorn": {
    "nextAvailable": "that morning, around early morning",
    "pushedForward": "the next morning"
  },
  "t-exact-0300__t-lbl-morn": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-exact-0300__t-lbl-lmorn": {
    "nextAvailable": "that morning, around late morning",
    "pushedForward": "the next morning"
  },
  "t-exact-0300__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-0300__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-0300__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-0300__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-exact-0300__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-0300__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-exact-0300__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-exact-0300__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-0300__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-exact-0300__t-exact-0300": {
    "nextAvailable": "right after, around 3:00 AM",
    "pushedForward": "the next day, around 3:00 AM"
  },
  "t-exact-0300__t-exact-0830": {
    "nextAvailable": "5 and a half hours later, around 8:30 AM",
    "pushedForward": "the next day, around 8:30 AM"
  },
  "t-exact-0300__t-exact-1200": {
    "nextAvailable": "9 hours later, around noon",
    "pushedForward": "the next day, around noon"
  },
  "t-exact-0300__t-exact-1400": {
    "nextAvailable": "11 hours later, around 2:00 PM",
    "pushedForward": "the next day, around 2:00 PM"
  },
  "t-exact-0300__t-exact-1800": {
    "nextAvailable": "15 hours later, around 6:00 PM",
    "pushedForward": "the next day, around 6:00 PM"
  },
  "t-exact-0300__t-exact-2100": {
    "nextAvailable": "18 hours later, around 9:00 PM",
    "pushedForward": "the next day, around 9:00 PM"
  },
  "t-exact-0300__t-exact-2330": {
    "nextAvailable": "20 hours later, around 11:30 PM",
    "pushedForward": "the next day, around 11:30 PM"
  },
  "t-exact-0830__t-none": {
    "nextAvailable": "later that morning",
    "pushedForward": "the next morning"
  },
  "t-exact-0830__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-exact-0830__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-exact-0830__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-0830__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-0830__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-exact-0830__t-lbl-emorn": {
    "nextAvailable": "still that morning, around early morning",
    "pushedForward": "the next morning"
  },
  "t-exact-0830__t-lbl-morn": {
    "nextAvailable": "still that morning",
    "pushedForward": "the next morning"
  },
  "t-exact-0830__t-lbl-lmorn": {
    "nextAvailable": "still that morning, around late morning",
    "pushedForward": "the next morning"
  },
  "t-exact-0830__t-lbl-noon": {
    "nextAvailable": "that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-0830__t-lbl-aft": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-0830__t-lbl-laft": {
    "nextAvailable": "that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-0830__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-exact-0830__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-0830__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-exact-0830__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-exact-0830__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-0830__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-exact-0830__t-exact-0300": {
    "nextAvailable": "the next day, around 3:00 AM",
    "pushedForward": "the next day, around 3:00 AM"
  },
  "t-exact-0830__t-exact-0830": {
    "nextAvailable": "right after, around 8:30 AM",
    "pushedForward": "the next day, around 8:30 AM"
  },
  "t-exact-0830__t-exact-1200": {
    "nextAvailable": "3 and a half hours later, around noon",
    "pushedForward": "the next day, around noon"
  },
  "t-exact-0830__t-exact-1400": {
    "nextAvailable": "5 and a half hours later, around 2:00 PM",
    "pushedForward": "the next day, around 2:00 PM"
  },
  "t-exact-0830__t-exact-1800": {
    "nextAvailable": "10 hours later, around 6:00 PM",
    "pushedForward": "the next day, around 6:00 PM"
  },
  "t-exact-0830__t-exact-2100": {
    "nextAvailable": "12 hours later, around 9:00 PM",
    "pushedForward": "the next day, around 9:00 PM"
  },
  "t-exact-0830__t-exact-2330": {
    "nextAvailable": "15 hours later, around 11:30 PM",
    "pushedForward": "the next day, around 11:30 PM"
  },
  "t-exact-1200__t-none": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1200__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-exact-1200__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-exact-1200__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1200__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1200__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1200__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1200__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1200__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1200__t-lbl-noon": {
    "nextAvailable": "still that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1200__t-lbl-aft": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1200__t-lbl-laft": {
    "nextAvailable": "still that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1200__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-exact-1200__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-1200__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-exact-1200__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-exact-1200__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-1200__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-exact-1200__t-exact-0300": {
    "nextAvailable": "the next day, around 3:00 AM",
    "pushedForward": "the next day, around 3:00 AM"
  },
  "t-exact-1200__t-exact-0830": {
    "nextAvailable": "the next day, around 8:30 AM",
    "pushedForward": "the next day, around 8:30 AM"
  },
  "t-exact-1200__t-exact-1200": {
    "nextAvailable": "right after, around noon",
    "pushedForward": "the next day, around noon"
  },
  "t-exact-1200__t-exact-1400": {
    "nextAvailable": "2 hours later, around 2:00 PM",
    "pushedForward": "the next day, around 2:00 PM"
  },
  "t-exact-1200__t-exact-1800": {
    "nextAvailable": "6 hours later, around 6:00 PM",
    "pushedForward": "the next day, around 6:00 PM"
  },
  "t-exact-1200__t-exact-2100": {
    "nextAvailable": "9 hours later, around 9:00 PM",
    "pushedForward": "the next day, around 9:00 PM"
  },
  "t-exact-1200__t-exact-2330": {
    "nextAvailable": "12 hours later, around 11:30 PM",
    "pushedForward": "the next day, around 11:30 PM"
  },
  "t-exact-1400__t-none": {
    "nextAvailable": "later that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1400__t-broad-day": {
    "nextAvailable": "later that day",
    "pushedForward": "the next day"
  },
  "t-exact-1400__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the following night"
  },
  "t-exact-1400__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1400__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1400__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1400__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1400__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1400__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1400__t-lbl-noon": {
    "nextAvailable": "still that afternoon, around noon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1400__t-lbl-aft": {
    "nextAvailable": "still that afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1400__t-lbl-laft": {
    "nextAvailable": "still that afternoon, around late afternoon",
    "pushedForward": "the next afternoon"
  },
  "t-exact-1400__t-lbl-sunset": {
    "nextAvailable": "that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-exact-1400__t-lbl-eve": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-1400__t-lbl-dusk": {
    "nextAvailable": "that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-exact-1400__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-exact-1400__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-1400__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-exact-1400__t-exact-0300": {
    "nextAvailable": "the next day, around 3:00 AM",
    "pushedForward": "the next day, around 3:00 AM"
  },
  "t-exact-1400__t-exact-0830": {
    "nextAvailable": "the next day, around 8:30 AM",
    "pushedForward": "the next day, around 8:30 AM"
  },
  "t-exact-1400__t-exact-1200": {
    "nextAvailable": "the next day, around noon",
    "pushedForward": "the next day, around noon"
  },
  "t-exact-1400__t-exact-1400": {
    "nextAvailable": "right after, around 2:00 PM",
    "pushedForward": "the next day, around 2:00 PM"
  },
  "t-exact-1400__t-exact-1800": {
    "nextAvailable": "4 hours later, around 6:00 PM",
    "pushedForward": "the next day, around 6:00 PM"
  },
  "t-exact-1400__t-exact-2100": {
    "nextAvailable": "7 hours later, around 9:00 PM",
    "pushedForward": "the next day, around 9:00 PM"
  },
  "t-exact-1400__t-exact-2330": {
    "nextAvailable": "10 hours later, around 11:30 PM",
    "pushedForward": "the next day, around 11:30 PM"
  },
  "t-exact-1800__t-none": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-1800__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-exact-1800__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-1800__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1800__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1800__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-exact-1800__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1800__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1800__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-1800__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-1800__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-1800__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-1800__t-lbl-sunset": {
    "nextAvailable": "still that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-exact-1800__t-lbl-eve": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-1800__t-lbl-dusk": {
    "nextAvailable": "still that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-exact-1800__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-exact-1800__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-1800__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-exact-1800__t-exact-0300": {
    "nextAvailable": "the next day, around 3:00 AM",
    "pushedForward": "the next day, around 3:00 AM"
  },
  "t-exact-1800__t-exact-0830": {
    "nextAvailable": "the next day, around 8:30 AM",
    "pushedForward": "the next day, around 8:30 AM"
  },
  "t-exact-1800__t-exact-1200": {
    "nextAvailable": "the next day, around noon",
    "pushedForward": "the next day, around noon"
  },
  "t-exact-1800__t-exact-1400": {
    "nextAvailable": "the next day, around 2:00 PM",
    "pushedForward": "the next day, around 2:00 PM"
  },
  "t-exact-1800__t-exact-1800": {
    "nextAvailable": "right after, around 6:00 PM",
    "pushedForward": "the next day, around 6:00 PM"
  },
  "t-exact-1800__t-exact-2100": {
    "nextAvailable": "3 hours later, around 9:00 PM",
    "pushedForward": "the next day, around 9:00 PM"
  },
  "t-exact-1800__t-exact-2330": {
    "nextAvailable": "5 and a half hours later, around 11:30 PM",
    "pushedForward": "the next day, around 11:30 PM"
  },
  "t-exact-2100__t-none": {
    "nextAvailable": "later that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-2100__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-exact-2100__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-2100__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-2100__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-2100__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-exact-2100__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-2100__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-2100__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-2100__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-2100__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-2100__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-2100__t-lbl-sunset": {
    "nextAvailable": "still that evening, around sunset",
    "pushedForward": "the next evening"
  },
  "t-exact-2100__t-lbl-eve": {
    "nextAvailable": "still that evening",
    "pushedForward": "the next evening"
  },
  "t-exact-2100__t-lbl-dusk": {
    "nextAvailable": "still that evening, around dusk",
    "pushedForward": "the next evening"
  },
  "t-exact-2100__t-lbl-enight": {
    "nextAvailable": "that night, around early night",
    "pushedForward": "the next night"
  },
  "t-exact-2100__t-lbl-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-2100__t-lbl-mid": {
    "nextAvailable": "that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-exact-2100__t-exact-0300": {
    "nextAvailable": "the next day, around 3:00 AM",
    "pushedForward": "the next day, around 3:00 AM"
  },
  "t-exact-2100__t-exact-0830": {
    "nextAvailable": "the next day, around 8:30 AM",
    "pushedForward": "the next day, around 8:30 AM"
  },
  "t-exact-2100__t-exact-1200": {
    "nextAvailable": "the next day, around noon",
    "pushedForward": "the next day, around noon"
  },
  "t-exact-2100__t-exact-1400": {
    "nextAvailable": "the next day, around 2:00 PM",
    "pushedForward": "the next day, around 2:00 PM"
  },
  "t-exact-2100__t-exact-1800": {
    "nextAvailable": "the next day, around 6:00 PM",
    "pushedForward": "the next day, around 6:00 PM"
  },
  "t-exact-2100__t-exact-2100": {
    "nextAvailable": "right after, around 9:00 PM",
    "pushedForward": "the next day, around 9:00 PM"
  },
  "t-exact-2100__t-exact-2330": {
    "nextAvailable": "2 and a half hours later, around 11:30 PM",
    "pushedForward": "the next day, around 11:30 PM"
  },
  "t-exact-2330__t-none": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-2330__t-broad-day": {
    "nextAvailable": "the next day",
    "pushedForward": "the day after"
  },
  "t-exact-2330__t-broad-night": {
    "nextAvailable": "later that night",
    "pushedForward": "the next night"
  },
  "t-exact-2330__t-lbl-predawn": {
    "nextAvailable": "the next dawn, around pre-dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-2330__t-lbl-dawn": {
    "nextAvailable": "the next dawn",
    "pushedForward": "the dawn after that"
  },
  "t-exact-2330__t-lbl-sunrise": {
    "nextAvailable": "the next dawn, around sunrise",
    "pushedForward": "the dawn after that"
  },
  "t-exact-2330__t-lbl-emorn": {
    "nextAvailable": "the next morning, around early morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-2330__t-lbl-morn": {
    "nextAvailable": "the next morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-2330__t-lbl-lmorn": {
    "nextAvailable": "the next morning, around late morning",
    "pushedForward": "the morning after that"
  },
  "t-exact-2330__t-lbl-noon": {
    "nextAvailable": "the next afternoon, around noon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-2330__t-lbl-aft": {
    "nextAvailable": "the next afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-2330__t-lbl-laft": {
    "nextAvailable": "the next afternoon, around late afternoon",
    "pushedForward": "the afternoon after that"
  },
  "t-exact-2330__t-lbl-sunset": {
    "nextAvailable": "the next evening, around sunset",
    "pushedForward": "the evening after that"
  },
  "t-exact-2330__t-lbl-eve": {
    "nextAvailable": "the next evening",
    "pushedForward": "the evening after that"
  },
  "t-exact-2330__t-lbl-dusk": {
    "nextAvailable": "the next evening, around dusk",
    "pushedForward": "the evening after that"
  },
  "t-exact-2330__t-lbl-enight": {
    "nextAvailable": "still that night, around early night",
    "pushedForward": "the next night"
  },
  "t-exact-2330__t-lbl-night": {
    "nextAvailable": "still that night",
    "pushedForward": "the next night"
  },
  "t-exact-2330__t-lbl-mid": {
    "nextAvailable": "still that night, around midnight",
    "pushedForward": "the next night"
  },
  "t-exact-2330__t-exact-0300": {
    "nextAvailable": "the next day, around 3:00 AM",
    "pushedForward": "the next day, around 3:00 AM"
  },
  "t-exact-2330__t-exact-0830": {
    "nextAvailable": "the next day, around 8:30 AM",
    "pushedForward": "the next day, around 8:30 AM"
  },
  "t-exact-2330__t-exact-1200": {
    "nextAvailable": "the next day, around noon",
    "pushedForward": "the next day, around noon"
  },
  "t-exact-2330__t-exact-1400": {
    "nextAvailable": "the next day, around 2:00 PM",
    "pushedForward": "the next day, around 2:00 PM"
  },
  "t-exact-2330__t-exact-1800": {
    "nextAvailable": "the next day, around 6:00 PM",
    "pushedForward": "the next day, around 6:00 PM"
  },
  "t-exact-2330__t-exact-2100": {
    "nextAvailable": "the next day, around 9:00 PM",
    "pushedForward": "the next day, around 9:00 PM"
  },
  "t-exact-2330__t-exact-2330": {
    "nextAvailable": "right after, around 11:30 PM",
    "pushedForward": "the next day, around 11:30 PM"
  }
}
